repos:
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [--line-length=120]

# - repo: https://github.com/pycqa/isort
#   rev: 5.10.1
#   hooks:
#     - id: isort
#       name: isort (python)