repos:
-   repo: https://github.com/python/black
    # issue related to click: https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click
    rev: 22.3.0
    hooks:
    - id: black
      args: [--line-length=120]

# - repo: https://github.com/pycqa/isort
#   rev: 5.10.1
#   hooks:
#     - id: isort
#       name: isort (python)